export class InformacionFamiliar {
    tiene_esposa:string;
    nombre_esposa:string;
    profesion_ocupacion_esposa:string;
    empresa_trabaja_esposa:string;
    cargo_actual_esposa:string;
    direccion_esposa:string;
    telefono_esposa:string;
    ciudad_esposa:string;

    numero_personas_dependen:number;
    nombres_parentesco:string;
    parentesco:string;
    edad:string;
    nombre_padre:string;
    profesion_ocupacion_padre:string;
    telefono_padre:string;
    nombre_madre:string;
    profesion_ocupacion_madre:string;
    telefono_madre:string;
    tiene_hermanos:string;
    nombre_hermano:string;
    profesion_ocupacion_hermano:string;
    telefono_hermano:string;
    nombre_hermano2:string;
    profesion_ocupacion_hermano2:string;
    telefono_hermano2:string;
    nombre_hermano3:string;
    profesion_ocupacion_hermano3:string;
    telefono_hermano3:string;
    nombre_hermano4:string;
    profesion_ocupacion_hermano4:string;
    telefono_hermano4:string;
}
